/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model.glb 
Author: VRChat Preview (https://sketchfab.com/Vrchat_preview)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vrchat-lurie-abd3fece996846aab5fb94662995652f
Title: [VRchat] Lurie
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/model.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_224.geometry} material={materials.Cloth2} skeleton={nodes.Object_224.skeleton} />
        <skinnedMesh geometry={nodes.Object_225.geometry} material={materials.ClothTransparent} skeleton={nodes.Object_225.skeleton} />
        <skinnedMesh geometry={nodes.Object_227.geometry} material={materials.Body} skeleton={nodes.Object_227.skeleton} />
        <skinnedMesh geometry={nodes.Object_228.geometry} material={materials.Expression} skeleton={nodes.Object_228.skeleton} />
        <skinnedMesh geometry={nodes.Object_229.geometry} material={materials.material} skeleton={nodes.Object_229.skeleton} />
        <skinnedMesh geometry={nodes.Object_230.geometry} material={materials.ExpressionTearFlow} skeleton={nodes.Object_230.skeleton} />
        <skinnedMesh geometry={nodes.Object_232.geometry} material={materials.Body2} skeleton={nodes.Object_232.skeleton} />
        <skinnedMesh geometry={nodes.Object_234.geometry} material={materials.Cloth} skeleton={nodes.Object_234.skeleton} />
        <skinnedMesh geometry={nodes.Object_236.geometry} material={materials.Cloth} skeleton={nodes.Object_236.skeleton} />
        <skinnedMesh geometry={nodes.Object_238.geometry} material={materials.Cloth2} skeleton={nodes.Object_238.skeleton} />
        <skinnedMesh geometry={nodes.Object_240.geometry} material={materials.Cloth2} skeleton={nodes.Object_240.skeleton} />
        <skinnedMesh geometry={nodes.Object_241.geometry} material={materials.ClothTransparent} skeleton={nodes.Object_241.skeleton} />
        <skinnedMesh geometry={nodes.Object_243.geometry} material={materials.Cloth} skeleton={nodes.Object_243.skeleton} />
        <skinnedMesh geometry={nodes.Object_245.geometry} material={materials.Cloth} skeleton={nodes.Object_245.skeleton} />
        <skinnedMesh geometry={nodes.Object_247.geometry} material={materials.Cloth2} skeleton={nodes.Object_247.skeleton} />
        <skinnedMesh geometry={nodes.Object_249.geometry} material={materials.Cloth} skeleton={nodes.Object_249.skeleton} />
        <skinnedMesh geometry={nodes.Object_251.geometry} material={materials.Cloth2} skeleton={nodes.Object_251.skeleton} />
        <skinnedMesh geometry={nodes.Object_253.geometry} material={materials.Cloth} skeleton={nodes.Object_253.skeleton} />
        <skinnedMesh geometry={nodes.Object_255.geometry} material={materials.Cloth2} skeleton={nodes.Object_255.skeleton} />
        <skinnedMesh geometry={nodes.Object_256.geometry} material={materials.ClothTransparent} skeleton={nodes.Object_256.skeleton} />
        <skinnedMesh geometry={nodes.Object_258.geometry} material={materials.Hair} skeleton={nodes.Object_258.skeleton} />
        <skinnedMesh geometry={nodes.Object_259.geometry} material={materials.HairFront} skeleton={nodes.Object_259.skeleton} />
        <skinnedMesh geometry={nodes.Object_261.geometry} material={materials.Cloth2} skeleton={nodes.Object_261.skeleton} />
        <skinnedMesh geometry={nodes.Object_263.geometry} material={materials.Cloth2} skeleton={nodes.Object_263.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
